### ISSUE TITLE
Fix typos in the documentation

### ISSUE THREAD

**Issue by raul1991** [rapidsai/frigate#16]
- I saw a word ```extent``` instead of ``` extend ```
- the template given on the doc uses ```markdown.jinja``` which should ```markdown.jinja2 ```
- The word ```.friagte``` should be changed to ```.frigate```

I could not edit the doc page since that is giving me a 404. May be we should correct that url ?

Nevertheless this tool is awesome.

**Comment by jacobtomlinson** [comment]
Thanks for pointing this out. It would be great to see you raise a PR to fix these.

Have a go at editing things on GitHub like [here](https://github.com/rapidsai/frigate/blob/branch-0.3/docs/customizing.rst).

**Comment by raul1991** [comment]
@jacobtomlinson I think this is now a duplicate issue. See #18
