### ISSUE TITLE
Is there a way to generate all the values from the dependent charts as well ?

### ISSUE THREAD

**Issue by raul1991** [rapidsai/frigate#21]
Parent-chart
   |_____ charts/
                    |_____ chart-1/values.yaml
                    |_____ chart-2/values.yaml

can frigate generate values collecting from all of them in one readme file ?

**Comment by jacobtomlinson** [comment]
Yes this was added in #11 and will be in the next release.

If you want this functionality now you can install the latest dev branch.

```
pip install git+https://github.com/rapidsai/frigate.git#branch-0.3
```

**Comment by raul1991** [comment]
Oh nice. I didn't new pip could do a remote install. I had to build it from the source :D
