### ISSUE TITLE
Pre-commit integration

### ISSUE THREAD

**Issue by jrottenberg** [rapidsai/frigate#33]
Hello !

Great utility, one way to get more adoption would be to provide an integration with pre-commit. 

https://pre-commit.com/

For terraform, for example, I have been using : https://github.com/antonbabenko/pre-commit-terraform

And the modules are always well documented, without worrying about it.

The flow would be : 

1. the chart maintainer installs the pre-commit hook
2. Update the chart's value, etc
3. Commit the change
4. pre-commit kicks in and run frigates, updating the README
5. User is prompted to add the change on the README.

**Comment by jrottenberg** [comment]
No feedback ? I wanted to see if there was any interest and submit a PR ;-/

Anyhow I wrote one and definitely it wouldn't have been simple to integrate with the current gen.py :

- requirement to specify the path to the chart
- get standard out to a file

See : https://github.com/jrottenberg/pre-commit-hooks/blob/main/pre_commit_hooks/frigate.py

**Comment by jacobtomlinson** [comment]
Sorry this seemed like spam at first glance, I must've been tired.

We are aware of pre-commit, see other repos in our org like [cudf](https://github.com/rapidsai/cudf) or [rmm](https://github.com/rapidsai/rmm). Being able to include Frigate in your pre-commit hooks would be awesome.

Very happy to review PRs.

**Comment by jrottenberg** [comment]
It did seem spammy, all good.

I'd like to see if you are interested of hosting a pre-commit hook directly (not from my own repo)

I can just copy the frigate.py utility I wrote and add it to the entry_points.console_scripts as `frigate/pre_commit_hooks.py`

OR 

patch gen.py to support : 
1. chart discovery (if no chart path is passed as parameter - potential breaking change for the users) 
2. Add a new parameter to capture the file output path

**Comment by jacobtomlinson** [comment]
Yeah absolutely. I think adding your file and setting up the entrypoints makes sense.

**Comment by jrottenberg** [comment]
@jacobtomlinson let me know if you'd like to see anything else.
