### ISSUE TITLE
Use `main` as the default branch

### ISSUE THREAD

**Issue by consideRatio** [rapidsai/frigate#45]
If possible, I suggest that `main` is the default branch used by this project, instead of the branch `branch-0.6`.

If not, I as a contributor ends up with questions like:
- Should I open a PR to the `main` branch, or the `branch-0.6` branch?
- Should I include the documentation commit in `branch-0.6` that isn't part of `main`?
- How does the `gh` CLI i use to quickly make commits work now, hmm...

To switch the default branch of this project, visit https://github.com/rapidsai/frigate/settings/branches. You can either delete the current main and rename the `branch-0.6` branch, or you can just switch the default branch from `branch-0.6` to `main`, and then have it be updated to include the documentation commit that `branch-0.6` has that `main` doesn't yet have.

Btw, I also note that https://github.com/rapidsai/frigate/pull/23 is a PR that looks to merge into `branch-0.3`, which would be very irrelevant now to do.

**Comment by jacobtomlinson** [comment]
In RAPIDS we have a project-wide workflow that uses the `branch-*` model of having a release targeted branch as the default. This seems mostly motivated by code freeze and having a "current" and "next" branch and being able to target features into specific releases.

Switching away from this process would be a large change affecting many different developers and projects. It is unlikely the RAPIDS ops folks are motivated to do that.

Making a PR to the default branch is the expected workflow here.

**Comment by consideRatio** [comment]
@jacobtomlinson ah, then maybe the main branch could be deleted as one incremental improvement to reduce the risk of additional confusion.
